[package]
name = "aesthetics"
version = "0.1.0"
authors = ["Alexander Davidson Bryan <alex.davidsonbryan@gmail.com>"]

[dependencies]
glium = "0.23.0"
nalgebra-glm = "0.1.3"
itertools = "0.7.8"
specs = "0.14.0"
specs-derive = "0.3.0"
shred = "0.7.1"
shred-derive = "0.5.1"
